# Configure main menu and social menu

# Socials

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/maxcheatle"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/maxcheatle"

[social.params]
icon = "linkedin"

# Menu List

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "cv"
name = "CV"
url = "/cv"
weight = 2

[main.params]
icon = "cv"
newtab = false
